#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$STAGED_FILES" ] && exit 0

# Type check
echo "Type checking..."
yarn --silent tsc --pretty false
TSC_EXIT_CODE=$?

# Format all staged files ignoring unknown extensions
echo "Formatting..."
echo "$STAGED_FILES" | xargs yarn --silent prettier --ignore-unknown --no-color --write --loglevel=warn
PRETTIER_EXIT_CODE=$?

# Get staged files allowed by tsconfig/eslint
# Ideally eslint would ignore unprocessable file extensions
TSCONFIG_STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR '*.tsx' '*.ts' '*.cjs' '*.mjs' '*.json' | sed 's| |\\ |g')

# Lint
echo "Linting..."
echo "$TSCONFIG_STAGED_FILES" | xargs yarn --silent eslint --no-color
ESLINT_EXIT_CODE=$?

# Return error exit code if any commands had errors
[[ $TSC_EXIT_CODE -eq 1 || $PRETTIER_EXIT_CODE -eq 1 || $ESLINT_EXIT_CODE -eq 1 ]] && exit 1

# Add back the modified files to staging
echo "$STAGED_FILES" | xargs git add
exit 0
